version: "3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
        container_name: ruby_demo
        working_dir: /var/www
        volumes:
            - ../blog:/var/www
            - bundle_cache:/bundle_cache
        environment:
            - BUNDLE_PATH=/bundle_cache
        ports:
            - 8081:3000
        networks:
            - app-networks
    bundle_cache:
        image: busybox
        volumes:
            - bundle_cache:/bundle_cache
        networks:
            - app-networks
    mysql:
        image: mysql:8.0.2
        container_name: db-ruby
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blogs
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=2213
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/sql:/docker-entrypoint-initdb.d
        networks:
            - app-networks
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ruby_phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db-ruby
            - PMA_USER=docker
            - PMA_PASSWORD=docker
        ports:
            - 8080:80
        networks:
            - app-networks
volumes:
    bundle_cache:
networks:
    app-networks:
        driver: bridge
